### ISSUE TITLE
実績解除の実装

### ISSUE THREAD

**Issue by nasubi916** [SystemEngineeringTeam/esachievement#100]
実績管理画面(`/unlocked`)で選択した実績を解除したことをDBに保存する｡

以前に作ってもらった関数を使用して実際に動かす

現状submit用のボタンが無いので仮で作成してもらってOK｡

@wappon28dev の実装が完了し次第､@kinako1415 にsubmitボタンの位置とかデザイン頼む←依頼済み

**Comment by wappon28dev** [comment]
https://github.com/user-attachments/assets/6f28e206-2ea6-4b75-9707-1a3f9af9590f
