### ISSUE TITLE
ranking画面が表示できなくなるバグ対応

### ISSUE THREAD

**Issue by nasubi916** [SystemEngineeringTeam/esachievement#105]

**Comment by wappon28dev** [comment]
色んなランタイムエラーの主な原因が分かったので, ここで共有しておきたいと思います.

1. `/members` や `/ranking` に遷移するときに `data.map is not function` みたいな TypeError が出る.  
→ SWR の key が重複していた.

https://github.com/SystemEngineeringTeam/esachievement/blob/2e19af83382218bd4e6969427dc858606921fc7f/src/pages/members/index.tsx#L23-L28

https://github.com/SystemEngineeringTeam/esachievement/blob/2e19af83382218bd4e6969427dc858606921fc7f/src/pages/ranking/index.tsx#L51-L59

この 2 つの SWR について, 第 2 引数の Promise (= fetcher) が fulfilled のときの `data` 型がそれぞれ `MembersWithUnlockedCount` と `{ unlockedAchievements: UnlockedAchievement[]; membersWithUnlockedCount: MembersWithUnlockedCount; }` のように異なるにも関わらず同じ key である `membersWithUnlockedCount` が使われていました.
SWR は, 同じ key のリクエストに対して適切なキャッシュを返すので, 直接 `/members` や `/ranking` にアクセスしたときには正しくレンダーされて, ヘッダーにあるナビゲーションから遷移したときは, セッションにキャッシュが残っているので SWR 側が型に合わないデータを返していたので, エラーが起こっていたことが分かりました.

`/members` → `/ranking` へ遷移するとき…
1. `/member` で SWR が key: `membersWithUnlockedCount` に対して `membersWithUnlockedCount` (= `Array<...>`) 型のデータをキャッシュする
