### ISSUE TITLE
esa API のモックを実装

### ISSUE THREAD

**Issue by wappon28dev** [SystemEngineeringTeam/esachievement#91]
開発中, HMR などで esa API の呼び出し制限に引っかかることが多々あるようです.  
呼び出し制限に引っかかるとクライアントエラーとなるので, スタイルの変更などの開発がしにくくなってしまっているようです.

なので, コンポーネント側のコードはあまり触らずに esa API のモックを提供するのがこの Issue の目標です.  
esa API を Wrap しているカスタムフック (`useMember`, `useTeam`, ...) に手を加えて開発環境のみモックに切り替わるようにするとスムーズに実装できるかと思います.

あいにく, 私は十分なお時間が取れないので, @nasubi916 に実装は任せたいと思います.

---

参考までに, 関係ありそうなモジュールと, それらの関係だけお伝えしておきます:

- 参加しているチームや単一のチームを選択するためのフック → [`useMember`](https://github.com/SystemEngineeringTeam/esachievement/blob/5c357b686ade542f7ed3a17b38fdbfbedcb5afc9/src/hooks/member.ts)  
- 単一のチームに対してのすべての操作 (チームのメンバーや esa への書き込みなど) のためのフック → [`useTeam`](https://github.com/SystemEngineeringTeam/esachievement/blob/5c357b686ade542f7ed3a17b38fdbfbedcb5afc9/src/hooks/teams.ts)
  - 複数チームに所属している場面のために, 選択されたチーム ([`selectedTeam`](https://github.com/SystemEngineeringTeam/esachievement/blob/5c357b686ade542f7ed3a17b38fdbfbedcb5afc9/src/lib/stores/teams.ts)) を nanostore が持っていなければ, エラーを Throw する.  
     (これも `useMember` に依存させるべきだった気が……  この Issue に対する PR で一緒に変えちゃっても OK です. 🙃)
  - Achievements や UnlockedAchievements の操作を提供するカスタムフックは, `useTeam` 自体を引数に持っており, `useTeam` に (わざと) 依存している.

つまり…

1. `useMember` や `useTeam` が依存している `esaClient` と全く同じ型を持つモックを気合いでベタ書きする.  
   (`as const satisfies T` などで縛ってあげるとこのプロジェクトの当初のような型が合わないモックによる悲劇を防ぐことができます.)
2.  [環境変数とモード - Vite ↗](https://ja.vitejs.dev/guide/env-and-mode.html#env-variables) を参考にして, 開発環境のみモックに切り替わるようなﾔｰﾂを実装する
3. 2 で作ったﾔｰﾂを注入できるよう, `useMember` や `useTeam` に良い感じの引数を作ってあげる.

あくまで一例で, 想像できるのはここまでが限界なので, 実装中に困った点があれば私に聞くか, 自分で方針変えちゃって実装して OK です！ 🙌

**Comment by nasubi916** [comment]
esaClientのモックを用意しようと思ったんですけど､私にはわかりませんでした(泣)

API上でモックに切り替わる方向ではなく､手動でモックに切り替える方向にしました｡
理由→→→
開発環境でAPIを叩きたい場合もあると思うので､Mockを参照するかAPIを叩くか切替可能にしてます

型が合わない悲劇を起こさないために､Mockを用意するのではなくAPIから取得したデータをlocalstorageに保存してモックとして使用する｡初回にAPIを叩くけど問題であった回数制限は回避できるからOKでしょ多分

(眠いから日本語終わってる)

**Comment by nasubi916** [comment]
useSWRとかパターンマッチングがわからない｡これ使えばAPIが叩けるようになるのは分かった｡

**Comment by wappon28dev** [comment]
`esaClient` のモックの作り方についてですが, [Testing - OpenAPI TypeScript Docs ↗](https://openapi-ts.pages.dev/openapi-fetch/testing) あたりに詳しく書いてそうなので見てみると良いと思います. 👀    見やすく書けるならライブラリの追加導入も OK です.

開発環境で API を叩きたい場合ですか……  その場合は `USE_MOCK` などの環境変数を用意して手動で対応するのはどうでしょう？  
モックを使うか使わないかで `USE_MOCK: 0 | 1` (default: `1`) のようにしてあげて, 本番環境のとき, モックは使わないので `USE_MOCK` は無視する方針で...  みたいな.

もちろん, 自動で切り替わる `autoMock` やモックである `mock` を用意して, `useTeam(autoMock)`, `useTeam(mock)` などでモックかそうじゃないかを引数で渡してあげるのもアリですが, やはり呼び出し側のコードの変更は避けたいところですね.

モックを作らずにキャッシュでなんとかする方法ですか.  まあ, API から返されるデータは, ある意味イミュータブルなのでそれもアリかもしれません.  
SWR にはフォーカス時のデータの再検証 (API にリクエストを送ってデータを最新にする挙動) があって, [`useSWRImmutable`](https://swr.vercel.app/ja/docs/revalidation#disable-automatic-revalidations) を使って自動検証を無効にするのを試してみても良いかもしれません.

また, LocalStorage を使ってキャッシュを試みる方法ですが, ちょうど SWR にその機能があったので共有しておきます:
https://swr.vercel.app/ja/docs/advanced/cache.ja#localstorage-based-persistent-cache
キャッシュプロバイダーとしてそのまま LocalStorage を使う書き方のようですね.  賢い.
(一貫性のために nanostore の store を定義して... でも一見良さそうですが, 外部から変更されては困るので, nanostore の store を使うことはここではオススメしません.)

SWR まわりのデバッグには, SWR から [開発者ツール](https://swr.vercel.app/ja/docs/advanced/devtools) が出ているので, 導入するとスムーズに開発できると思います.  ぜひ.
